# Site Configs
name: Ionic Framework
description: The official Ionic Framework blog
url: http://ionicframework.com/blog
markdown: kramdown
kramdown:
  input: GFM
timezone: "US/Central"
highlighter: rouge

# Default news if the page didnt enter news
news: Check out our <a href="/docs/guide/">Guide</a>, which covers all the basics of setting up.
v2news: Check out our <a href="/docs/v2/guide/">Guide</a>, which covers all the basics of setting up.
exclude: [node_modules, scss, README.md, Gulpfile.js]

# Latest Version Config
latest_download: http://code.ionicframework.com/1.2.4/ionic-v1.2.4.zip
latest_version: 1.2.4 "Copenhagen"
latest_release_date: 2016-01-02

# Which version of AngularJS the latest build includes
included_angular_version: 1.4.3

# Which active Cordova version we recommend
recommended_cordova_version: 5.1.1

# the primary plunkr to fork
code_sample_base_url: http://plnkr.co/edit/vD0O9M?p=preview

# default vars
